import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "@fortawesome/fontawesome-free/css/all.min.css";
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';
import GamePage from '../components/GamePage';

export default function Game() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Caste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GamePage/>
    </div>
  )
}
